# Generated by Django 4.0.6 on 2022-07-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
