# Generated by Django 4.0.6 on 2022-08-18 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nota', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantillas.plantilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
