# Generated by Django 4.0.6 on 2022-07-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_alter_datos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateField(),
        ),
    ]
