# Generated by Django 4.0.6 on 2022-11-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limite',
            name='limite',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
