# Generated by Django 4.0.6 on 2022-11-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_alter_limite_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limite',
            name='limite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
