# Generated by Django 4.0.6 on 2022-07-27 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntos_medicion', '0002_puntomedicion_created_at_puntomedicion_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntomedicion',
            name='tipo',
        ),
    ]
