# Generated by Django 4.0.6 on 2022-09-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(default='Sin Contacto', max_length=100),
        ),
    ]
